# Generated by Django 5.2.4 on 2025-07-03 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('icon', models.CharField(default='fas fa-book', max_length=50, verbose_name='Icon')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_main', models.CharField(max_length=20, verbose_name='Asosiy telefon')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name="Qo'shimcha telefon")),
                ('email_main', models.EmailField(max_length=254, verbose_name='Asosiy email')),
                ('email_support', models.EmailField(blank=True, max_length=254, verbose_name='Yordam email')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('working_hours', models.TextField(verbose_name='Ish vaqti')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
            ],
            options={
                'verbose_name': "Aloqa ma'lumotlari",
                'verbose_name_plural': "Aloqa ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('surname', models.CharField(max_length=100, verbose_name='Familiya')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Savol-Javob',
                'verbose_name_plural': 'Savol-Javoblar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Filial nomi')),
                ('district', models.CharField(max_length=100, verbose_name='Tuman')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Ish vaqti')),
                ('capacity', models.IntegerField(verbose_name="Sig'im")),
                ('image', models.ImageField(blank=True, upload_to='locations/', verbose_name='Rasm')),
                ('features', models.TextField(help_text='Har bir xususiyatni yangi qatordan yozing', verbose_name='Imkoniyatlar')),
                ('transport', models.TextField(help_text='Har bir transport turini yangi qatordan yozing', verbose_name='Transport')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_main', models.BooleanField(default=False, verbose_name='Bosh filial')),
                ('opened_date', models.DateField(auto_now_add=True, verbose_name='Ochilgan sana')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'ordering': ['-is_main', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Xizmat nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('icon', models.CharField(default='fas fa-star', max_length=50, verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_count', models.IntegerField(default=500, verbose_name="O'quvchilar soni")),
                ('teachers_count', models.IntegerField(default=50, verbose_name="O'qituvchilar soni")),
                ('courses_count', models.IntegerField(default=30, verbose_name='Kurslar soni')),
                ('experience_years', models.IntegerField(default=5, verbose_name='Tajriba yillari')),
            ],
            options={
                'verbose_name': 'Sayt statistikasi',
                'verbose_name_plural': 'Sayt statistikasi',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism Familiya')),
                ('specialty', models.CharField(max_length=100, verbose_name='Mutaxassislik')),
                ('bio', models.TextField(verbose_name='Biografiya')),
                ('experience', models.CharField(choices=[('1-2', '1-2 yil'), ('3-5', '3-5 yil'), ('5-10', '5-10 yil'), ('10+', '10+ yil')], max_length=10, verbose_name='Tajriba')),
                ('students_count', models.IntegerField(default=0, verbose_name="O'quvchilar soni")),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Reyting')),
                ('photo', models.ImageField(blank=True, upload_to='teachers/', verbose_name='Rasm')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('skills', models.TextField(help_text="Har bir ko'nikmani yangi qatordan yozing", verbose_name="Ko'nikmalar")),
                ('languages', models.TextField(help_text='Har bir tilni yangi qatordan yozing', verbose_name='Tillar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_featured', models.BooleanField(default=False, verbose_name="Asosiy o'qituvchi")),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
                'ordering': ['-joined_date'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('course', models.CharField(max_length=100, verbose_name='Kurs')),
                ('message', models.TextField(verbose_name='Fikr')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Reyting')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Fikr',
                'verbose_name_plural': 'Fikrlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kurs nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('level', models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Yuqori')], max_length=20, verbose_name='Daraja')),
                ('duration_months', models.IntegerField(default=3, verbose_name='Davomiyligi (oy)')),
                ('students_count', models.IntegerField(default=0, verbose_name="O'quvchilar soni")),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Reyting')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Narx (so'm)")),
                ('instructor', models.CharField(max_length=100, verbose_name="O'qituvchi")),
                ('image', models.ImageField(blank=True, upload_to='courses/', verbose_name='Rasm')),
                ('features', models.TextField(help_text='Har bir xususiyatni yangi qatordan yozing', verbose_name='Xususiyatlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mashhur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['-created_at'],
            },
        ),
    ]
